apiVersion: v1
kind: Service
metadata:
  name: {{ include "lms-sparrow-fe-chart.fullname" . }}-lms-frontend-svc
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: lms-frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}