apiVersion: v1
kind: ConfigMap
metadata:
  name: judge0-config
data:
  judge0.conf: |
    # Judge0 Configuration File
    JUDGE0_TELEMETRY_ENABLE=true
    RESTART_MAX_TRIES=3
    MAX_SUBMISSION_BATCH_SIZE=10
    CALLBACKS_MAX_TRIES=2
    CALLBACKS_TIMEOUT=3

    # Judge0 Workers Configuration
    INTERVAL=0.2
    COUNT=2

    # Redis Configuration
    REDIS_HOST=redis-svc
    REDIS_PORT=6379
    REDIS_PASSWORD=${REDIS_PASSWORD}

    # PostgreSQL Configuration
    POSTGRES_HOST=postgres-svc
    POSTGRES_PORT=5432
    POSTGRES_DB=judge0
    POSTGRES_USER=judge0
    POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    # Submission Configuration
    CPU_TIME_LIMIT=2
    MAX_CPU_TIME_LIMIT=15
    CPU_EXTRA_TIME=0.5
    MAX_CPU_EXTRA_TIME=2
    WALL_TIME_LIMIT=5
    MEMORY_LIMIT=256000
    MAX_MEMORY_LIMIT=256000
    MAX_PROCESSES_AND_OR_THREADS=30
    MAX_MAX_PROCESSES_AND_OR_THREADS=60
    ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
    ALLOW_ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
    ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true
    ALLOW_ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true
    ENABLE_NETWORK=true

    # Rails Configuration
    RAILS_ENV=production
    RAILS_MAX_THREADS=2
    RAILS_SERVER_PROCESSES=1
    SECRET_KEY_BASE=
