---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  type: {{ .Values.compiler.service.type }}
  selector:
    app: server
  ports:
  - protocol: TCP
    port: {{ .Values.compiler.service.port }}
    targetPort: {{ .Values.compiler.service.targetPort }}