apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lms-sparrow-compiler-chart.fullname" . }}-postgres-pod
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.repository }}
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.postgres.resources.requests.memory }}
              cpu: {{ .Values.postgres.resources.requests.cpu }}          
            limits:
              memory: {{ .Values.postgres.resources.limits.memory }}        
              cpu: {{ .Values.postgres.resources.limits.cpu }}        
          ports:
            - containerPort: {{ .Values.postgres.service.targetPort }}
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: judge0-secrets
                key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim