apiVersion: v1
kind: PersistentVolume
metadata:
  name: lms-compiler-redis-pv
  labels:
    type: local
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data