apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: {{ .Values.storageClass.provisioner }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
parameters:
  {{- range $key, $value := .Values.storageClass.parameters }}
  {{ $key }}: {{ $value }}
  {{- end }}