apiVersion: v1
kind: Service
metadata:
  name: {{ include "lms-sparrow-ui-chart.fullname" . }}-lms-landing-svc
spec:
  type: {{ .Values.landing.service.type }}
  selector:
    app: lms-landing
  ports:
  - port: {{ .Values.landing.service.port }}
    targetPort: {{ .Values.landing.service.targetPort }}
